blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support (from config.yml)
    url: https://github.community/
    about: Please ask and answer questions here (from config.yml).
  - name: GitHub Security Bug Bounty (from config.yml)
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here (from config.yml).
